// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs-YusLEXfU7UNbLihiBkY-y6zg8q5HNI',
    appId: '1:455799022843:web:49c238632e0570ee69fc5e',
    messagingSenderId: '455799022843',
    projectId: 'prueba-app-5bb53',
    authDomain: 'prueba-app-5bb53.firebaseapp.com',
    databaseURL: 'https://prueba-app-5bb53-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-app-5bb53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZtJtuUEyyC4ISY5lfCbUZDcUrzoE5wI',
    appId: '1:455799022843:android:3c1eaa2ccb0145fb69fc5e',
    messagingSenderId: '455799022843',
    projectId: 'prueba-app-5bb53',
    databaseURL: 'https://prueba-app-5bb53-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-app-5bb53.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFCffZV28ul7WHmASWzwZYu7qQURu5Sw',
    appId: '1:455799022843:web:1d6701a19fd4b93d69fc5e',
    messagingSenderId: '455799022843',
    projectId: 'prueba-app-5bb53',
    authDomain: 'prueba-app-5bb53.firebaseapp.com',
    databaseURL: 'https://prueba-app-5bb53-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-app-5bb53.firebasestorage.app',
  );
}
